// Convert hex color to RGB array
function hexToRgb(hex) {
    const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
    return result ? [
      parseInt(result[1], 16),
      parseInt(result[2], 16),
      parseInt(result[3], 16)
    ] : [0, 0, 0];
  }
  
  // Convert hex color to RGB array
  function hexToRgb(hex) {
    const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
    return result ? [
      parseInt(result[1], 16),
      parseInt(result[2], 16),
      parseInt(result[3], 16)
    ] : [0, 0, 0];
  }
  
  // UI State Management
  const bgTypeSelect = document.getElementById('bgType');
  const solidGroup = document.getElementById('solidColorGroup');
  const gradientGroup = document.getElementById('gradientColorGroup');
  const imageGroup = document.getElementById('imageUploadGroup');
  
  bgTypeSelect.addEventListener('change', () => {
    const type = bgTypeSelect.value;
    solidGroup.style.display = type === 'solid' ? 'block' : 'none';
    gradientGroup.style.display = type === 'gradient' ? 'block' : 'none';
    imageGroup.style.display = type === 'image' ? 'block' : 'none';
  });
  
  // Helper to create a gradient image blob
  function createGradientBlob(c1, c2, c3) {
    return new Promise((resolve) => {
      const canvas = document.createElement('canvas');
      canvas.width = 1920; // Standard HD width
      canvas.height = 1080;
      const ctx = canvas.getContext('2d');
  
      // Create linear gradient (top to bottom)
      const gradient = ctx.createLinearGradient(0, 0, 0, canvas.height);
      gradient.addColorStop(0, c1);
      gradient.addColorStop(0.5, c2);
      gradient.addColorStop(1, c3);
  
      ctx.fillStyle = gradient;
      ctx.fillRect(0, 0, canvas.width, canvas.height);
  
      canvas.toBlob((blob) => {
        resolve(blob);
      }, 'image/png');
    });
  }
  
  // Handle the "Confirm" Button
  document.getElementById('confirmBtn').addEventListener('click', async () => {
    const themeName = document.getElementById('themeName').value || "My Custom Theme";
  
    // Common colors
    const frameRGB = hexToRgb(document.getElementById('frameColor').value);
    const toolbarRGB = hexToRgb(document.getElementById('toolbarColor').value);
    const textRGB = [0, 0, 0]; // Default black
  
    // Background Processing
    const bgType = bgTypeSelect.value;
    let bgBlob = null;
    let solidBgRGB = null;
  
    try {
      if (bgType === 'gradient') {
        const c1 = document.getElementById('gradColor1').value;
        const c2 = document.getElementById('gradColor2').value;
        const c3 = document.getElementById('gradColor3').value;
        bgBlob = await createGradientBlob(c1, c2, c3);
      } else if (bgType === 'image') {
        const fileInput = document.getElementById('bgImageFile');
        if (fileInput.files.length > 0) {
          bgBlob = fileInput.files[0];
        }
      } else {
        // Solid Color
        solidBgRGB = hexToRgb(document.getElementById('bgColor').value);
      }
    } catch (e) {
      console.error("Error preparing background:", e);
      alert("Error preparing background image.");
      return;
    }
  
    // Construct Manifest
    const manifest = {
      "manifest_version": 3,
      "version": "1.0",
      "name": themeName,
      "description": "Custom theme generated by extension.",
      "theme": {
        "colors": {
          "frame": frameRGB,
          "toolbar": toolbarRGB,
          "ntp_text": textRGB,
          "tab_text": textRGB,
          "tab_background_text": [255, 255, 255],
          "button_background": toolbarRGB
        }
      }
    };
  
    // Add background specific properties
    if (bgBlob) {
      manifest.theme.images = {
        "theme_ntp_background": "background.png"
      };
      manifest.theme.properties = {
        "ntp_background_alignment": "center",
        "ntp_background_repeat": "no-repeat"
      };
      // Ensure text is readable if no solid bg color is set (or set a fallback)
      manifest.theme.colors.ntp_background = [255, 255, 255]; // Fallback common white
    } else if (solidBgRGB) {
      manifest.theme.colors.ntp_background = solidBgRGB;
    }
  
    // Generate Download
    if (bgBlob) {
      // We need to zip it
      const zip = new JSZip();
      zip.file("manifest.json", JSON.stringify(manifest, null, 2));
      zip.file("background.png", bgBlob);
  
      const content = await zip.generateAsync({ type: "blob" });
      downloadFile(content, "theme.zip");
    } else {
      // Just JSON
      const jsonString = JSON.stringify(manifest, null, 2);
      const blob = new Blob([jsonString], { type: "application/json" });
      downloadFile(blob, "manifest.json");
    }
  });
  
  function downloadFile(blob, filename) {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }